openapi: 3.1.0
info:
  title: FreeLancing
  description: This is Get the User data
  version: 1.0.0
  contact: {}
  servers:
    - url: "https://api.ekalakaar.com/api/v1"
      description: Production mode
    - url: "http://localhost:4000/api/auth/"
      description: Development mode
paths:
  /:
    get:
      summary: Get user details of a particular user by id
      tags:
        - Query
      description: this is root get method
      responses:
        200:
          description: success done
        400:
          description: somthink want wronge

  /api/auth/register:
    post:
      tags:
        - User Registration
      summary: Register a new user
      description: >-
        Use this endpoint to register a new user with the provided information.
        The following fields are required:
          - firstName
          - lastName
          - email
          - phoneNumber
          - password
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
                last:
                  type: string
                  example: Doe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                number:
                  type: string
                  example: "+1234567890"
                password:
                  type: string
                  format: password
                  example: Password123
      responses:
        "201":
          description: User registered successfully

  /api/auth/login:
    post:
      tags:
        - User Login
      summary: Log in an existing user
      description: >-
        Use this endpoint to Login.
        The following fields are required:
          - email
          - password
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  security: []
      responses:
        "201":
          description: Successfully loggedin
  /api/auth/admin:
    get:
      tags: 
        - Admin Login
      summary: Get access token for admin login
      description: >-
        Use this endpoint to Login.
        The following fields are required:
          - email
          - password
      security:
         - JWTAuth: []
      description: Admin-only route
      responses:
        200:
          description: Admin access granted
        401:
          description: Unauthorized
        403:
          description: Forbidden (not an admin)
